server:
  port: 8081

spring:
  application:
    name: ms-client-service
  datasource:
    url: jdbc:h2:mem:clients
    username: sa
    password:
    driverClassName: org.h2.Driver
card:
  getcards:
    url: "http://localhost:8082/api/v1/cards"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/